name: Build
on:
  push:
    branches-ignore:
      - release
    tags-ignore:
      - 'published/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm ci
    - name: tsc
      run: |
        npx tsc -p .
        npx vsce package
